config/routes.rb
FileServer::Application.routes.draw do
  resources :sounds

end

app/models/sound.rb
class Sound < ActiveRecord::Base
  attr_accessible :sound_file, :text
  mount_uploader :sound_file, SoundFileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sounds_controller.rb
require 'speech'

class SoundsController < ApplicationController
  # GET /sounds
  # GET /sounds.json
  def index
    @sounds = Sound.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sounds }
    end
  end

  # GET /sounds/1
  # GET /sounds/1.json
  def show
    @sound = Sound.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sound }
    end
  end

  # GET /sounds/new
  # GET /sounds/new.json
  def new
    @sound = Sound.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sound }
    end
  end

  # GET /sounds/1/edit
  def edit
    @sound = Sound.find(params[:id])
  end

  # POST /sounds
  # POST /sounds.json
  def create

    @sound = Sound.new(params[:sound])
    @sound.text = toText(@sound)

    respond_to do |format|
      if @sound.save
        format.html { redirect_to @sound, notice: 'Sound was successfully created.' }
        format.json { render json: @sound, status: :created, location: @sound, text: @sound.text }
      else
        format.html { render action: "new" }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sounds/1
  # PUT /sounds/1.json
  def update
    @sound = Sound.find(params[:id])

    respond_to do |format|
      if (@sound.update_attributes(params[:sound]) && @sound.update_attributes(:text => toText(@sound)))
        format.html { redirect_to @sound, notice: 'Sound was successfully updated.' }
        format.json { render json: @sound, status: :updated, location: @sound, text: @sound.text }
      else
        format.html { render action: "edit" }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sounds/1
  # DELETE /sounds/1.json
  def destroy
    @sound = Sound.find(params[:id])
    @sound.destroy

    respond_to do |format|
      format.html { redirect_to sounds_url }
      format.json { head :no_content }
    end
  end

  private

  # Given a Sound, locate the asset in the file system, convert it to text, and return the text.

  def toText(sound)
    rails_root_dir = Rails.root.to_s
    public_dir = "/public"
    sound_file_dir = sound.sound_file.to_s
    sound_file_path = rails_root_dir + public_dir + sound_file_dir
    audio = Speech::AudioToText.new(sound_file_path, :verbose => true)
    text = audio.to_text
    return text
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sounds/_form.html.erb
<%= form_for @sound, html: { multipart: true } do |f| %>
  <% if @sound.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sound.errors.count, "error") %> prohibited this sound from being saved:</h2>

      <ul>
      <% @sound.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sound_file %><br />
    <%= f.file_field :sound_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sounds/edit.html.erb
<h1>Editing sound</h1>

<%= render 'form' %>

<%= link_to 'Show', @sound %> |
<%= link_to 'Back', sounds_path %>

app/views/sounds/index.html.erb
<h1>Listing sounds</h1>

<table>
  <tr>
    <th>Sound file</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sounds.each do |sound| %>
  <tr>
    <td><%= sound.sound_file %></td>
    <td><%= sound.text %></td>
    <td><%= link_to 'Show', sound %></td>
    <td><%= link_to 'Edit', edit_sound_path(sound) %></td>
    <td><%= link_to 'Destroy', sound, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sound', new_sound_path %>

app/views/sounds/new.html.erb
<h1>New sound</h1>

<%= render 'form' %>

<%= link_to 'Back', sounds_path %>

app/views/sounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sound file:</b>
  <%= @sound.sound_file %>
</p>

<p>
  <b>Text:</b>
  <%= @sound.text %>
</p>


<%= link_to 'Edit', edit_sound_path(@sound) %> |
<%= link_to 'Back', sounds_path %>